DROP_PARK = '''
    DROP TABLE IF EXISTS PARK;
'''

DROP_SLOT = '''
    DROP TABLE IF EXISTS SLOT;
'''

DROP_COMPANY = '''
    DROP TABLE IF EXISTS COMPANY;
'''

GENERATE_PARK = '''
    CREATE TABLE PARK (
        ID INT PRIMARY KEY NOT NULL,
        NAME TEXT NOT NULL,
        SLOT INT NOT NULL
    );
'''

GENERATE_SLOT = '''
    CREATE TABLE SLOT (
        ID INT PRIMARY KEY NOT NULL,
        ID_PARK INT NOT NULL,
        STATUS BOOLEAN
    );
'''

INSERT_PARK = '''INSERT INTO PARK (ID,NAME,SLOT) VALUES (?,?,?)'''